// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_ClusterContent)
QT_DECLARE_EXTERN_RESOURCE(qmake_ClusterContent)
QT_DECLARE_EXTERN_RESOURCE(ClusterContent_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_ClusterContent)

class ClusterContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    ClusterContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_ClusterContent)
QT_KEEP_RESOURCE(qmlcache_ClusterContent)
QT_KEEP_RESOURCE(qmake_ClusterContent)
QT_KEEP_RESOURCE(ClusterContent_raw_qml_0)
    }
};



#include "ClusterContentplugin_ClusterContentPlugin.moc"
