// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_Cluster)
QT_DECLARE_EXTERN_RESOURCE(qmake_Cluster)
QT_DECLARE_EXTERN_RESOURCE(Cluster_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Cluster)

class ClusterPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    ClusterPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Cluster)
QT_KEEP_RESOURCE(qmlcache_Cluster)
QT_KEEP_RESOURCE(qmake_Cluster)
QT_KEEP_RESOURCE(Cluster_raw_qml_0)
    }
};



#include "Clusterplugin_ClusterPlugin.moc"
